### ISSUE TITLE
metadata.yaml has invalid YAML formatting.

### ISSUE THREAD

**Issue by philpott** [Allan-Urique/GTM_CustomTag_AwinLastClickIdentifier#1]
Your metadata.yaml file has invalid formatting in the versions list (notice the sha and changeNotes parameters are not aligned. Using a YAML validator will help verify fixes

To view your templates update status you can follow along on the [status page](
https://tagmanager.google.com/gallery/#/template/Allan-Urique/GTM_CustomTag_AwinLastClickIdentifier/status)

**Comment by Allan-Urique** [comment]
> Your metadata.yaml file has invalid formatting in the versions list (notice the sha and changeNotes parameters are not aligned. Using a YAML validator will help verify fixes
> 
> To view your templates update status you can follow along on the [status page](https://tagmanager.google.com/gallery/#/template/Allan-Urique/GTM_CustomTag_AwinLastClickIdentifier/status)

Great! Thanks for the heads up @philpott, I've now updated the metadata file, should be good to go! :)
